### ISSUE TITLE
Which branch/commit is compatible with ROCm 1.6?

### ISSUE THREAD

**Issue by mattsinc** [ROCmSoftwarePlatform/Thrust#25]
I am attempting to run some benchmarks that use thrust in them through the gem5 simulator, which currently only supports ROCm 1.6.x. While hipify'ing the applications, I need to port the thrust calls to use rocThrust (which I did). However, after looking through the release tags and the commits for rocThrust, it appears that rocThrust only supports ROCm 2.5+. I've verified this with the rocThrust folks here: https://github.com/ROCmSoftwarePlatform/rocThrust/issues/70

They directed me to this repo.  I looked through the various branches, and I see one for ROCm 1.5, so it seems support for ROCm 1.6 is possible.  I don't see a separate branch for ROCm 1.6 though.  Do you know which branch (or commit on that branch) I should be using?  It seems like it's roughly around this commit: https://github.com/ROCmSoftwarePlatform/Thrust/commit/5aa0c4d7ba8922aa305425dfa70cfab72535390b, since the next commit is for ROCm 1.7.1?

Thanks,
Matt

**Comment by saadrahim** [comment]
Hello again, sorry but I cannot be of much more assistance to you. Please try the 1.5 or 1.7 branch. This library has been replaced by rocThrust as it has a more efficient back-end. Thrust is a header only library, so the 1.5 version should compile on 1.6.

**Comment by mattsinc** [comment]
@saadrahim : yeah, I realized after posting we may be communicating again :)

Ok, thanks.  We'll give that a try.

Matt
