### ISSUE TITLE
Incorrect header organization leading to (thrust::cuda::par not found)

### ISSUE THREAD

**Issue by Jorghi12** [ROCmSoftwarePlatform/Thrust#9]
Hi! I'm noticing that the headers for the ROCm port of Thrust has a minor mistake.

On the CUDA version of Thrust, I only need to include these two headers
#include <thrust/device_ptr.h>
#include <thrust/sequence.h>
to be able to use **thrust::cuda::par**

While I can simply include **#include <thrust/execution_policy.h>** and solve the issue, it would be nice to have the headers correctly set up in the ROCm port so that transpilation will be more seamless for HIP in general (all these little changes here or there add up!).

**Comment by sriharikarnam** [comment]
@Jorghi12 We currently do not see the above error in the HIP Port.Can you tell us exactly the use case for which you encounter the above error or share the log so that we could look into it clearly.
